name: SimpleArtifact

on:
  push:
  
jobs:
    work:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - run: mkdir -p path/to/artifact
      - run: echo HELLO_WORLD > path/to/artifact/hello_world.txt
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/helo_world.txt
    work1:
      runs-on: ubuntu-latest
      steps: 
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
         name: my-artifact
         path: path/to/artifact
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifact
